// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKZ5RVtY9kD98aCIWQCq3Exm65Hs_DvnI',
    appId: '1:601179809013:web:bc23ffb8f4e11428fc51bc',
    messagingSenderId: '601179809013',
    projectId: 'covs-fatec',
    authDomain: 'covs-fatec.firebaseapp.com',
    storageBucket: 'covs-fatec.firebasestorage.app',
    measurementId: 'G-0YHR2801Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1SMjiPlEWCiCbks7EVGIFfxMBygWLo5o',
    appId: '1:601179809013:android:6d8c63a45c79ad23fc51bc',
    messagingSenderId: '601179809013',
    projectId: 'covs-fatec',
    storageBucket: 'covs-fatec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVSOPZUBEkFn9_Lv2zOkCNBmSzosyX4iM',
    appId: '1:601179809013:ios:97db830efa069ef6fc51bc',
    messagingSenderId: '601179809013',
    projectId: 'covs-fatec',
    storageBucket: 'covs-fatec.firebasestorage.app',
    iosBundleId: 'com.example.volatileConnect',
  );
}
